### ISSUE TITLE
LMSSplitter (KeepAlive): Fehler beim KeepAlive

### ISSUE THREAD

**Issue by BlueSnake830** [Nall-chan/SqueezeBox#5]
Hallo,

ich habe stündlich diese Fehlermeldung:

Absender: TimerPool
Nachricht: LMSSplitter (KeepAlive): Fehler beim KeepAlive

Es wird IP-Symcon 6.0 Stable eingesetzt.

![image](https://user-images.githubusercontent.com/75618694/145800761-7866e3bc-1f32-4d3a-b967-21886d80ab78.png)

**Comment by Nall-chan** [comment]
Tritt der Fehler mit der aktuellen Version und IPS 6.1 noch immer auf?

**Comment by Nall-chan** [comment]
Support sonst bitte hier m Forum:
https://community.symcon.de/t/modul-squeezebox-release/46937
